server:
  port: ${user-service.port}

spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: ${nacos.server-address}
        group: ${nacos.group}
        file-extension: ${nacos.file-extension}
    feign:
      discovery:
        enabled: true
      hystrix:
        enabled: false

jwt:
  secret-key: 2ad5af5f-85cd-4423-b443-7a4ec30072f7

logging:
  level:
    org.springframework: DEBUG